### ISSUE TITLE
LS not working on first try

### ISSUE THREAD

**Issue by glklimmer** [edizeqiri/unishell#10]
Command `ls` does not work when executed as first command.

1. Start Unishell
2. Type `ls`

Returns:
```
Unishell ( ͡ಠ ʖ̯ ͡ಠ ): No such file or directory
```

what should be returned: 

```
LICENSE  Makefile  README.md  Unishell  functions.c  functions.h  hosts  main.
```

Works on second try though.

**Comment by edizeqiri** [comment]
![grafik](https://user-images.githubusercontent.com/89740646/173204278-26e348be-5724-4640-b335-fbe9ecb4b380.png)
Worked first try on main branch

**Comment by edizeqiri** [comment]
I will analyze it tho.

**Comment by glklimmer** [comment]
Works now somehow. Might have been something with processes running.
