### ISSUE TITLE
Pomodoro

### ISSUE THREAD

**Issue by edizeqiri** [edizeqiri/unishell#3]
Implement Pomodoro timer in functions.c.

Inspiration of what [Pomodoro](https://pomofocus.io/) should do.

**Comment by edizeqiri** [comment]
Maybe [this](https://stackoverflow.com/questions/4708760/c-timers-and-threads-again) could help.

**Comment by glklimmer** [comment]
Thread should stop printing messages when other process was started, e.g. git diff.

**Comment by glklimmer** [comment]
Only take ASCII Letters into account to not freak out when pressing DEL for example.
